version: "2"

services:

  web:
    build: .

  redis:
    image: redis

  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
